package StokProgrami;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Database.DBoperations;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author clepz
 */
public class Analiz extends javax.swing.JPanel {

    /**
     * Creates new form Analiz
     */
    public Analiz() {
        initComponents();
        satisAnalizOlustur();
        alimAnalizOlustur();
        analizOlustur();

    }

    private void analizOlustur() {
        DBoperations dBoperations = DBoperations.createDBoperations();
        double gelir = dBoperations.toplamGelirMiktari();
        lbSatisToplam.setText(gelir+" TL");
        double gider = dBoperations.toplamGiderMiktari();
        lbFark.setHorizontalAlignment(SwingConstants.RIGHT);
        lbAlimToplam.setText("-"+gider + " TL");
        lbFark.setText(""+(gelir-gider + " TL"));
        dBoperations.stokAzListe(listStokAz);

        dBoperations.close();
    }

    private void alimAnalizOlustur() {
        DBoperations dBoperations = DBoperations.createDBoperations();
        dBoperations.alimAnalizTabloYap(tbAlimAnaliz);
        String kisi[] = dBoperations.enAzSatan();
        String urun[] = dBoperations.enAzSatanUrun();
        String gelir[] = dBoperations.enAzGelir();
        dBoperations.close();
        azSatisYapan.setText(kisi[0]);
        azSatisYapanMiktar.setText(kisi[1]);
        azSatilanUrun.setText(urun[0]);
        azSatilanUrunMiktar.setText(urun[1]);
        azGelirGetiren.setText(gelir[0]);
        azGelirGetirenTutar.setText(gelir[1]+" TL");

    }

    private void satisAnalizOlustur() {
        DBoperations dBoperations = DBoperations.createDBoperations();
        dBoperations.satisAnalizTabloYap(tbSatisAnaliz);
        String kisi[] = dBoperations.enCokSatan();
        String urun[] = dBoperations.enCokSatanUrun();
        String gelir[] = dBoperations.enCokGelir();
        dBoperations.close();
        cokSatisYapan.setText(kisi[0]);
        cokSatisYapanMiktar.setText(kisi[1]);
        cokSatilanUrun.setText(urun[0]);
        cokSatilanUrunMiktari.setText(urun[1]);
        cokGelirGetiren.setText(gelir[0]);
        cokGelirGetirenTutar.setText(gelir[1]+ " TL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSatisAnaliz = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSatisAnaliz = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cokSatisYapan = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cokSatisYapanMiktar = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cokSatilanUrun = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cokSatilanUrunMiktari = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cokGelirGetiren = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cokGelirGetirenTutar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        azSatisYapan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        azSatisYapanMiktar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        azSatilanUrun = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        azSatilanUrunMiktar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        azGelirGetiren = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        azGelirGetirenTutar = new javax.swing.JLabel();
        pnlAlimAnaliz = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAlimAnaliz = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        pnlAnaliz = new javax.swing.JPanel();
        lbAlimToplam = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbFark = new javax.swing.JLabel();
        lbSatisToplam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listStokAz = new javax.swing.JList<>();
        Font font = new Font("Comic Sans Ms" , Font.BOLD, 17);
        jLabel9.setFont(font);
        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel27.setFont(font);
        jLabel27.setHorizontalAlignment(SwingConstants.CENTER);

        setBackground(new java.awt.Color(208, 208, 208));
        setMinimumSize(new java.awt.Dimension(1200, 635));
        setPreferredSize(new java.awt.Dimension(1200, 635));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 68, 75));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ANALİZ");
        add(jLabel1);
        jLabel1.setBounds(320, 0, 579, 73);

        jTabbedPane1.setBackground(null);
        jTabbedPane1.setForeground(new java.awt.Color(1, 1, 1));
        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jTabbedPane1.setOpaque(false);

        pnlSatisAnaliz.setForeground(new java.awt.Color(1, 8, 16));
        pnlSatisAnaliz.setLayout(null);

        tbSatisAnaliz.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Tarih", "Kullanıcı Adı", "Satılan Urun", "Satılan Miktar", "Toplam Gelir"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSatisAnaliz.setRowHeight(20);
        tbAlimAnaliz.setRowHeight(20);
        tbSatisAnaliz.setFont(new Font("Arial" , Font.BOLD,15));
        tbAlimAnaliz.setFont(new Font("Arial" , Font.BOLD,15));
        jScrollPane1.setViewportView(tbSatisAnaliz);

        pnlSatisAnaliz.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 804, 547);

        jPanel1.setLayout(new java.awt.GridLayout(15, 2, 5, 5));

        jLabel27.setText("En Çok");
        jPanel1.add(jLabel27);
        jPanel1.add(jLabel3);

        jLabel21.setText("Satış Yapan:");
        jPanel1.add(jLabel21);
        jPanel1.add(cokSatisYapan);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Miktarı :");
        jPanel1.add(jLabel22);
        jPanel1.add(cokSatisYapanMiktar);

        jLabel25.setText("Satılan Ürün :");
        jPanel1.add(jLabel25);
        jPanel1.add(cokSatilanUrun);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Miktarı :");
        jPanel1.add(jLabel24);
        jPanel1.add(cokSatilanUrunMiktari);

        jLabel17.setText("Gelir Getiren :");
        jPanel1.add(jLabel17);
        jPanel1.add(cokGelirGetiren);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Tutar :");
        jPanel1.add(jLabel18);
        jPanel1.add(cokGelirGetirenTutar);
        jPanel1.add(jSeparator3);
        jPanel1.add(jSeparator2);

        jLabel9.setText("En Az");
        jPanel1.add(jLabel9);
        jPanel1.add(jLabel8);

        jLabel15.setText("Satış Yapan:");
        jPanel1.add(jLabel15);
        jPanel1.add(azSatisYapan);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Miktarı :");
        jPanel1.add(jLabel14);
        jPanel1.add(azSatisYapanMiktar);

        jLabel12.setText("Satılan Ürün :");
        jPanel1.add(jLabel12);
        jPanel1.add(azSatilanUrun);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Miktarı :");
        jPanel1.add(jLabel7);
        jPanel1.add(azSatilanUrunMiktar);

        jLabel10.setText("Gelir Getiren :");
        jPanel1.add(jLabel10);
        jPanel1.add(azGelirGetiren);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Tutar :");
        jPanel1.add(jLabel29);
        jPanel1.add(azGelirGetirenTutar);

        pnlSatisAnaliz.add(jPanel1);
        jPanel1.setBounds(810, 0, 370, 547);

        jTabbedPane1.addTab("Satış Analizi", pnlSatisAnaliz);

        pnlAlimAnaliz.setLayout(null);

        tbAlimAnaliz.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Tarih", "Ürün", "Alınan Yer/Kişi", "Miktar", "Tane Fiyatı", "Toplam Fiyat"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbAlimAnaliz);

        pnlAlimAnaliz.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 809, 535);

        jLabel5.setText("jLabel5");
        //pnlAlimAnaliz.add(jLabel5);
        jLabel5.setBounds(827, 12, 56, 23);

        jTabbedPane1.addTab("Alım Analizi", pnlAlimAnaliz);

        pnlAnaliz.setLayout(null);

        lbAlimToplam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAlimToplam.setBounds(257, 186, 122, 33);
        pnlAnaliz.add(jSeparator1);
        jSeparator1.setBounds(226, 256, 153, 15);

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/clepz/Downloads/toplama2.png")); // NOI18N
        pnlAnaliz.add(jLabel6);
        jLabel6.setBounds(226, 225, 25, 25);

        jLabel2.setText("Toplam Satış Geliri : ");
        pnlAnaliz.add(jLabel2);
        jLabel2.setBounds(59, 103, 180, 34);
        pnlAnaliz.add(lbFark);
        lbFark.setBounds(247, 277, 132, 34);

        lbSatisToplam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlAnaliz.add(lbSatisToplam);
        lbSatisToplam.setBounds(257, 103, 122, 34);

        jLabel4.setText("Toplam Alım Gideri:");
        pnlAnaliz.add(jLabel4);
        jLabel4.setBounds(59, 186, 180, 33);

        jLabel11.setText("Bitmekte Olan Ürünler");
        pnlAnaliz.add(jLabel11);
        jLabel11.setBounds(522, 52, 206, 34);

        listStokAz.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listStokAz.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listStokAz);

        pnlAnaliz.add(jScrollPane3);
        jScrollPane3.setBounds(522, 104, 206, 181);

        jTabbedPane1.addTab("Analiz", pnlAnaliz);

        add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 1200, 590);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JLabel azGelirGetiren;
    private javax.swing.JLabel azGelirGetirenTutar;
    private javax.swing.JLabel azSatilanUrun;
    private javax.swing.JLabel azSatilanUrunMiktar;
    private javax.swing.JLabel azSatisYapan;
    private javax.swing.JLabel azSatisYapanMiktar;
    private javax.swing.JLabel cokGelirGetiren;
    private javax.swing.JLabel cokGelirGetirenTutar;
    private javax.swing.JLabel cokSatilanUrun;
    private javax.swing.JLabel cokSatilanUrunMiktari;
    private javax.swing.JLabel cokSatisYapan;
    private javax.swing.JLabel cokSatisYapanMiktar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAlimToplam;
    private javax.swing.JLabel lbFark;
    private javax.swing.JLabel lbSatisToplam;
    private javax.swing.JList<String> listStokAz;
    private javax.swing.JPanel pnlAlimAnaliz;
    private javax.swing.JPanel pnlAnaliz;
    private javax.swing.JPanel pnlSatisAnaliz;
    private javax.swing.JTable tbAlimAnaliz;
    private javax.swing.JTable tbSatisAnaliz;
    // End of variables declaration
}



