package StokProgrami;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Database.DBoperations;
import Database.MusteriBilgi;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author clepz
 */
public class MusteriListe extends javax.swing.JPanel {

    /**
     * Creates new form musteriBilgiPanel
     */
    public MusteriListe() {
        initComponents();
        tumListe();

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfAdSoyad = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();

        setBackground(new java.awt.Color(208, 208, 208));
        setPreferredSize(new java.awt.Dimension(1200, 635));
        setLayout(null);

        jTable1.setBackground(new Color(204,204,204));
        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setRowHeight(25);
        jTable1.setRowMargin(3);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Ad-Soyad", "Telefon", "Adres", "Satın Alınan Ürün", "Toplam Fiyat", "Satan "
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(400);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 1140, 500);
        add(jLabel2);
        jLabel2.setBounds(980, 90, 180, 50);

        jLabel1.setBackground(java.awt.Color.black);
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Ad Soyad:");
        add(jLabel1);
        jLabel1.setBounds(270, 20, 140, 50);

        tfAdSoyad.setBackground(Color.GRAY);
        tfAdSoyad.setForeground(Color.BLACK);
        tfAdSoyad.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        tfAdSoyad.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent keyEvent) {
                if(tfAdSoyad.getText().length() == 0)
                    tumListe();
            }
        });
        add(tfAdSoyad);
        tfAdSoyad.setBounds(400, 20, 180, 50);

        btnAra.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                btnAraIslemler();
            }
        });
        btnAra.setIcon(new ImageIcon(getClass().getResource("/panelImage/ara.png")));
        btnAra.setBackground(null);
        btnAra.setBorder(null);
        add(btnAra);
        btnAra.setBounds(690, 20, 110, 50);


        JLabel iconPanel2 = new JLabel();
        iconPanel2.setIcon(new ImageIcon(getClass().getResource("/panelImage/tarik635.png")));
        add(iconPanel2);
        iconPanel2.setBounds(0,0,1200,635);
    }// </editor-fold>

    private void btnAraIslemler() {
        DBoperations dBoperations = DBoperations.createDBoperations();
        ArrayList<MusteriBilgi> liste = dBoperations.musteriBilgiAl(tfAdSoyad.getText());
        dBoperations.close();
        tabloOlustur(liste);
    }
    private void tabloOlustur(ArrayList<MusteriBilgi> liste){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        jTable1.revalidate();
        jTable1.repaint();
        while(!liste.isEmpty()) {
            MusteriBilgi musteri = liste.remove(0);
            model.addRow(new Object[]{musteri.getID(),musteri.getAdSoyad(),musteri.getTelefon(),musteri.getAdres(),musteri.getAldigiUrun(),
                    musteri.getFiyat(),musteri.getSatan()});
        }
    }
    private void tumListe() {
        DBoperations dBoperations = DBoperations.createDBoperations();
        ArrayList<MusteriBilgi> liste = dBoperations.musterListe();
        dBoperations.close();
        tabloOlustur(liste);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfAdSoyad;
    // End of variables declaration
}

